//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.8
//
// <auto-generated>
//
// Generated from file `CoffeMach.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package servicios;

public interface ServicioComMQCafe extends com.zeroc.Ice.Object
{
    void alarmaMaquina(int idAlarma, int idMaquina, java.util.Date fechaInicial, com.zeroc.Ice.Current current);

    void reporteVentas(int idMaquina, java.util.Date fechaInicial, java.util.Date fechaFinal, String[] detalle, com.zeroc.Ice.Current current);

    void desactivarAlarma(int idMaquina, int idAlarma, java.util.Date fechaFinal, com.zeroc.Ice.Current current);

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Ice::Object",
        "::servicios::ServicioComMQCafe"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::servicios::ServicioComMQCafe";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_alarmaMaquina(ServicioComMQCafe obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_idAlarma;
        int iceP_idMaquina;
        java.util.Date iceP_fechaInicial;
        iceP_idAlarma = istr.readInt();
        iceP_idMaquina = istr.readInt();
        iceP_fechaInicial = istr.readSerializable(java.util.Date.class);
        inS.endReadParams();
        obj.alarmaMaquina(iceP_idAlarma, iceP_idMaquina, iceP_fechaInicial, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_reporteVentas(ServicioComMQCafe obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_idMaquina;
        java.util.Date iceP_fechaInicial;
        java.util.Date iceP_fechaFinal;
        String[] iceP_detalle;
        iceP_idMaquina = istr.readInt();
        iceP_fechaInicial = istr.readSerializable(java.util.Date.class);
        iceP_fechaFinal = istr.readSerializable(java.util.Date.class);
        iceP_detalle = istr.readStringSeq();
        inS.endReadParams();
        obj.reporteVentas(iceP_idMaquina, iceP_fechaInicial, iceP_fechaFinal, iceP_detalle, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_desactivarAlarma(ServicioComMQCafe obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_idMaquina;
        int iceP_idAlarma;
        java.util.Date iceP_fechaFinal;
        iceP_idMaquina = istr.readInt();
        iceP_idAlarma = istr.readInt();
        iceP_fechaFinal = istr.readSerializable(java.util.Date.class);
        inS.endReadParams();
        obj.desactivarAlarma(iceP_idMaquina, iceP_idAlarma, iceP_fechaFinal, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "alarmaMaquina",
        "desactivarAlarma",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "reporteVentas"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_alarmaMaquina(this, in, current);
            }
            case 1:
            {
                return _iceD_desactivarAlarma(this, in, current);
            }
            case 2:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 3:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 4:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 5:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 6:
            {
                return _iceD_reporteVentas(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
