//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.8
//
// <auto-generated>
//
// Generated from file `CoffeMach.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package servicios;

public interface ServicioComMQCafePrx extends com.zeroc.Ice.ObjectPrx
{
    default void alarmaMaquina(int idAlarma, int idMaquina, java.util.Date fechaInicial)
    {
        alarmaMaquina(idAlarma, idMaquina, fechaInicial, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void alarmaMaquina(int idAlarma, int idMaquina, java.util.Date fechaInicial, java.util.Map<String, String> context)
    {
        _iceI_alarmaMaquinaAsync(idAlarma, idMaquina, fechaInicial, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> alarmaMaquinaAsync(int idAlarma, int idMaquina, java.util.Date fechaInicial)
    {
        return _iceI_alarmaMaquinaAsync(idAlarma, idMaquina, fechaInicial, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> alarmaMaquinaAsync(int idAlarma, int idMaquina, java.util.Date fechaInicial, java.util.Map<String, String> context)
    {
        return _iceI_alarmaMaquinaAsync(idAlarma, idMaquina, fechaInicial, context, false);
    }

    /**
     * @hidden
     * @param iceP_idAlarma -
     * @param iceP_idMaquina -
     * @param iceP_fechaInicial -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_alarmaMaquinaAsync(int iceP_idAlarma, int iceP_idMaquina, java.util.Date iceP_fechaInicial, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "alarmaMaquina", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeInt(iceP_idAlarma);
                     ostr.writeInt(iceP_idMaquina);
                     ostr.writeSerializable(iceP_fechaInicial);
                 }, null);
        return f;
    }

    default void reporteVentas(int idMaquina, java.util.Date fechaInicial, java.util.Date fechaFinal, String[] detalle)
    {
        reporteVentas(idMaquina, fechaInicial, fechaFinal, detalle, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void reporteVentas(int idMaquina, java.util.Date fechaInicial, java.util.Date fechaFinal, String[] detalle, java.util.Map<String, String> context)
    {
        _iceI_reporteVentasAsync(idMaquina, fechaInicial, fechaFinal, detalle, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> reporteVentasAsync(int idMaquina, java.util.Date fechaInicial, java.util.Date fechaFinal, String[] detalle)
    {
        return _iceI_reporteVentasAsync(idMaquina, fechaInicial, fechaFinal, detalle, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> reporteVentasAsync(int idMaquina, java.util.Date fechaInicial, java.util.Date fechaFinal, String[] detalle, java.util.Map<String, String> context)
    {
        return _iceI_reporteVentasAsync(idMaquina, fechaInicial, fechaFinal, detalle, context, false);
    }

    /**
     * @hidden
     * @param iceP_idMaquina -
     * @param iceP_fechaInicial -
     * @param iceP_fechaFinal -
     * @param iceP_detalle -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_reporteVentasAsync(int iceP_idMaquina, java.util.Date iceP_fechaInicial, java.util.Date iceP_fechaFinal, String[] iceP_detalle, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "reporteVentas", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeInt(iceP_idMaquina);
                     ostr.writeSerializable(iceP_fechaInicial);
                     ostr.writeSerializable(iceP_fechaFinal);
                     ostr.writeStringSeq(iceP_detalle);
                 }, null);
        return f;
    }

    default void desactivarAlarma(int idMaquina, int idAlarma, java.util.Date fechaFinal)
    {
        desactivarAlarma(idMaquina, idAlarma, fechaFinal, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void desactivarAlarma(int idMaquina, int idAlarma, java.util.Date fechaFinal, java.util.Map<String, String> context)
    {
        _iceI_desactivarAlarmaAsync(idMaquina, idAlarma, fechaFinal, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> desactivarAlarmaAsync(int idMaquina, int idAlarma, java.util.Date fechaFinal)
    {
        return _iceI_desactivarAlarmaAsync(idMaquina, idAlarma, fechaFinal, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> desactivarAlarmaAsync(int idMaquina, int idAlarma, java.util.Date fechaFinal, java.util.Map<String, String> context)
    {
        return _iceI_desactivarAlarmaAsync(idMaquina, idAlarma, fechaFinal, context, false);
    }

    /**
     * @hidden
     * @param iceP_idMaquina -
     * @param iceP_idAlarma -
     * @param iceP_fechaFinal -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_desactivarAlarmaAsync(int iceP_idMaquina, int iceP_idAlarma, java.util.Date iceP_fechaFinal, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "desactivarAlarma", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeInt(iceP_idMaquina);
                     ostr.writeInt(iceP_idAlarma);
                     ostr.writeSerializable(iceP_fechaFinal);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ServicioComMQCafePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ServicioComMQCafePrx.class, _ServicioComMQCafePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ServicioComMQCafePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ServicioComMQCafePrx.class, _ServicioComMQCafePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ServicioComMQCafePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ServicioComMQCafePrx.class, _ServicioComMQCafePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ServicioComMQCafePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ServicioComMQCafePrx.class, _ServicioComMQCafePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ServicioComMQCafePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ServicioComMQCafePrx.class, _ServicioComMQCafePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ServicioComMQCafePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ServicioComMQCafePrx.class, _ServicioComMQCafePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ServicioComMQCafePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ServicioComMQCafePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ServicioComMQCafePrx ice_adapterId(String newAdapterId)
    {
        return (ServicioComMQCafePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ServicioComMQCafePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ServicioComMQCafePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ServicioComMQCafePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ServicioComMQCafePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ServicioComMQCafePrx ice_invocationTimeout(int newTimeout)
    {
        return (ServicioComMQCafePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ServicioComMQCafePrx ice_connectionCached(boolean newCache)
    {
        return (ServicioComMQCafePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ServicioComMQCafePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ServicioComMQCafePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ServicioComMQCafePrx ice_secure(boolean b)
    {
        return (ServicioComMQCafePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ServicioComMQCafePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ServicioComMQCafePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ServicioComMQCafePrx ice_preferSecure(boolean b)
    {
        return (ServicioComMQCafePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ServicioComMQCafePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ServicioComMQCafePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ServicioComMQCafePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ServicioComMQCafePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ServicioComMQCafePrx ice_collocationOptimized(boolean b)
    {
        return (ServicioComMQCafePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ServicioComMQCafePrx ice_twoway()
    {
        return (ServicioComMQCafePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ServicioComMQCafePrx ice_oneway()
    {
        return (ServicioComMQCafePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ServicioComMQCafePrx ice_batchOneway()
    {
        return (ServicioComMQCafePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ServicioComMQCafePrx ice_datagram()
    {
        return (ServicioComMQCafePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ServicioComMQCafePrx ice_batchDatagram()
    {
        return (ServicioComMQCafePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ServicioComMQCafePrx ice_compress(boolean co)
    {
        return (ServicioComMQCafePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ServicioComMQCafePrx ice_timeout(int t)
    {
        return (ServicioComMQCafePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ServicioComMQCafePrx ice_connectionId(String connectionId)
    {
        return (ServicioComMQCafePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default ServicioComMQCafePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (ServicioComMQCafePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::servicios::ServicioComMQCafe";
    }
}
